services:
  #  backend:
  #    image: file_storage_rrtyui
  #    build:
  #      context: ./file_storage
  #    depends_on:
  #      db:
  #        condition: service_healthy
  #    environment:
  #      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
  #      SPRING_DATASOURCE_USERNAME: ${DB_USER}
  #      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
  redis:
    image: redis
    restart: always

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB: ${DB_NAME}}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5430:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: