spring:
  session:
    redis:
      namespace: spring:session
    timeout: 30m
  data:
    redis:
      host: redis
      port: 6379
  datasource:
      url: jdbc:postgresql://db:5432/file_storage
      username: hesaro_kan
      password: y768ayxxx
      driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB