minio:
  endpoint: http://minioS3:9000
  access-key: ${MINIO_APP_USER}
  secret-key: ${MINIO_APP_PASSWORD}

spring:

  liquibase:
    enabled: true

  session:
    redis:
      namespace: spring:session
    timeout: 60m

  data:
    redis:
      host: redis
      port: 6379

  datasource:
      url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver

  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB