#spring:
#  db:
#    url: jdbc:postgresql://db:5432/${DB_NAME}
#    name: ${DB_NAME}
#    password: ${DB_PASSWORD}
#    user: 123
#  application:
#      name: filestorage
spring:
    datasource:
        url: jdbc:postgresql://localhost:5430/file_storage
        username: hesaro_kan
        password: y768ayxxx
        driver-class-name: org.postgresql.Driver
    jpa:
        properties.hibernate:
            show_sql: true
            format_sql: true
